### ISSUE TITLE
Stworzenie widoku z logowaniem i rejestracją

### ISSUE THREAD

**Issue by Mensix** [koteczki01/time_management_web_app#20]
W folderze /frontend/pages w plikach signin.vue i signup.vue

**Comment by sarastec** [comment]
@Natkapietruszki213 - Logowanie
@danieldruzdzel - Rejestracja
Zwróćcie uwagę na to, że będziecie mieć wspólny layout i niektóre komponenty, więc będziecie musieli trochę współpracować. Projekty widoków są w przypiętych wiadomościach na frontendzie na dc.

**Comment by sarastec** [comment]
I nie róbcie w logowaniu tego paska na dole z logowaniem przez Google itp., bo na razie i tak nie będziemy tego implementować
